Mejoras en Bioterio
Errores:
crear jaula --> le asigna 0 al proyecto, entonces cuando lo traigo me da error en el GET.
eliminar jaula --> TypeError: laJaulaTieneAnimales() missing 1 required positional argument: 'idJaula'
Agregar:
Cuando me trae todos los blogs de todas las jaulas q tmb me traiga el codigo de la jaula.